# filename: docker-compose.yml
name: devops-ai

services:
  db:
    image: postgres:16
    container_name: devops-ai-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: src/app/api/Dockerfile
    container_name: devops-ai-api
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      API_PREFIX: ${API_PREFIX}
      LLM_PROVIDER: ${LLM_PROVIDER}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE__POSTGRES_DSN: ${DATABASE__POSTGRES_DSN}
      AUDIT_DB_URL: ${AUDIT_DB_URL}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    command: >
      sh -c "uvicorn app.api.main:app --host ${API_HOST} --port ${API_PORT} --workers 2"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${API_PORT}${API_PREFIX}/health || exit 1"]
    restart: unless-stopped

  mcp:
    build:
      context: .
      dockerfile: src/app/api/Dockerfile
    container_name: devops-ai-mcp
    environment:
      MCP_TRANSPORT: ${MCP_TRANSPORT}
      DATABASE_URL: ${DATABASE_URL}
      AUDIT_DB_URL: ${AUDIT_DB_URL}
      MEMORY_DB_URL: ${MEMORY_DB_URL}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python -m app.mcp.server"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: devops-ai-ollama
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 40
    restart: unless-stopped

volumes:
  dbdata: {}
  ollama: {}
