name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install uv
        run: pip install uv

      - name: Check lockfile
        run: uv lock --check

      - name: Install project and dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install --upgrade types-PyYAML

      - name: Validate build artifacts
        run: |
          python -m build
          ls -la dist

      - name: Ruff lint
        run: ruff check .

      - name: Black formatting check
        run: black --check .

      - name: Mypy type check
        run: mypy src

      #- name: Run tests
       # run: |
        #  mkdir -p reports
         # pytest --cov=src --cov-report=xml --junitxml=reports/junit.xml

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload junit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
